### PR TITLE
Fix deprecation warnings when compiling on OSX

### PR DESCRIPTION
**Pull request by lyssdod**
I've tested it locally and it solves the issue  (Xcode 8.0, OSX 10.11.6)

### CODE REVIEW

**Comment by lyssdod** [comment]
This will fix #10

**Comment by lyssdod** [comment]
It turned out that I had an old cache and it does not fix the warnings anymore. I think that adding `-Wno-deprecated-declarations` system-wide is too ignorant at this point, so let's wait for another boost release

**Comment by unbornchikken** [comment]
I'm lost. Should I merge or should I close?

**Comment by lyssdod** [comment]
I think better to close, since it's local problem

**Pull request closed without merging**
